// Optimized date-fns imports to reduce bundle size
// Only import the specific functions we need instead of the entire library

// Common date functions
export {
  format,
  parseISO,
  isValid,
  isToday,
  isYesterday,
  isTomorrow,
  isThisWeek,
  isThisMonth,
  isThisYear,
  startOfDay,
  endOfDay,
  startOfWeek,
  endOfWeek,
  startOfMonth,
  endOfMonth,
  startOfYear,
  endOfYear,
  addDays,
  subDays,
  addWeeks,
  subWeeks,
  addMonths,
  subMonths,
  addYears,
  subYears,
  differenceInDays,
  differenceInWeeks,
  differenceInMonths,
  differenceInYears,
  differenceInHours,
  differenceInMinutes,
  differenceInSeconds,
  isAfter,
  isBefore,
  isEqual,
  isSameDay,
  isSameWeek,
  isSameMonth,
  isSameYear,
  isWithinInterval,
  eachDayOfInterval,
  eachWeekOfInterval,
  eachMonthOfInterval,
  eachYearOfInterval,
  getDay,
  getWeek,
  getMonth,
  getYear,
  getHours,
  getMinutes,
  getSeconds,
  setDay,
  setWeek,
  setMonth,
  setYear,
  setHours,
  setMinutes,
  setSeconds,
  min,
  max,
  closestTo,
  closestIndexTo,
  isWeekend,
  isMonday,
  isTuesday,
  isWednesday,
  isThursday,
  isFriday,
  isSaturday,
  isSunday,
  getDayOfYear,
  getWeekYear,
  getQuarter,
  getISOWeeksInYear,
  getISOWeek,
  getISOWeekYear,
  setISOWeek,
  setISOWeekYear,
  getISODay,
  setISODay,
  isSameISOWeek,
  isSameISOWeekYear,
  isThisISOWeek,
  isLeapYear,
  getDaysInMonth,
  getDaysInYear,
  getWeeksInMonth,
  getISOWeeksInYear as getISOWeeksInYearAlt,
  getISOWeek as getISOWeekAlt,
  getISOWeekYear as getISOWeekYearAlt,
  setISOWeek as setISOWeekAlt,
  setISOWeekYear as setISOWeekYearAlt,
  getISODay as getISODayAlt,
  setISODay as setISODayAlt,
  isSameISOWeek as isSameISOWeekAlt,
  isSameISOWeekYear as isSameISOWeekYearAlt,
  isThisISOWeek as isThisISOWeekAlt,
  isLeapYear as isLeapYearAlt,
  getDaysInMonth as getDaysInMonthAlt,
  getDaysInYear as getDaysInYearAlt,
  getWeeksInMonth as getWeeksInMonthAlt,
} from 'date-fns';

// Jalali date functions
export {
  format as formatJalali,
  parseISO as parseJalaliISO,
  isValid as isValidJalali,
  isToday as isTodayJalali,
  isYesterday as isYesterdayJalali,
  isTomorrow as isTomorrowJalali,
  isThisWeek as isThisWeekJalali,
  isThisMonth as isThisMonthJalali,
  isThisYear as isThisYearJalali,
  startOfDay as startOfDayJalali,
  endOfDay as endOfDayJalali,
  startOfWeek as startOfWeekJalali,
  endOfWeek as endOfWeekJalali,
  startOfMonth as startOfMonthJalali,
  endOfMonth as endOfMonthJalali,
  startOfYear as startOfYearJalali,
  endOfYear as endOfYearJalali,
  addDays as addDaysJalali,
  subDays as subDaysJalali,
  addWeeks as addWeeksJalali,
  subWeeks as subWeeksJalali,
  addMonths as addMonthsJalali,
  subMonths as subMonthsJalali,
  addYears as addYearsJalali,
  subYears as subYearsJalali,
  differenceInDays as differenceInDaysJalali,
  differenceInWeeks as differenceInWeeksJalali,
  differenceInMonths as differenceInMonthsJalali,
  differenceInYears as differenceInYearsJalali,
  differenceInHours as differenceInHoursJalali,
  differenceInMinutes as differenceInMinutesJalali,
  differenceInSeconds as differenceInSecondsJalali,
  isAfter as isAfterJalali,
  isBefore as isBeforeJalali,
  isEqual as isEqualJalali,
  isSameDay as isSameDayJalali,
  isSameWeek as isSameWeekJalali,
  isSameMonth as isSameMonthJalali,
  isSameYear as isSameYearJalali,
  isWithinInterval as isWithinIntervalJalali,
  eachDayOfInterval as eachDayOfIntervalJalali,
  eachWeekOfInterval as eachWeekOfIntervalJalali,
  eachMonthOfInterval as eachMonthOfIntervalJalali,
  eachYearOfInterval as eachYearOfIntervalJalali,
  getDay as getDayJalali,
  getWeek as getWeekJalali,
  getMonth as getMonthJalali,
  getYear as getYearJalali,
  getHours as getHoursJalali,
  getMinutes as getMinutesJalali,
  getSeconds as getSecondsJalali,
  setDay as setDayJalali,
  setWeek as setWeekJalali,
  setMonth as setMonthJalali,
  setYear as setYearJalali,
  setHours as setHoursJalali,
  setMinutes as setMinutesJalali,
  setSeconds as setSecondsJalali,
  min as minJalali,
  max as maxJalali,
  closestTo as closestToJalali,
  closestIndexTo as closestIndexToJalali,
  isWeekend as isWeekendJalali,
  isMonday as isMondayJalali,
  isTuesday as isTuesdayJalali,
  isWednesday as isWednesdayJalali,
  isThursday as isThursdayJalali,
  isFriday as isFridayJalali,
  isSaturday as isSaturdayJalali,
  isSunday as isSundayJalali,
  getDayOfYear as getDayOfYearJalali,
  getWeekYear as getWeekYearJalali,
  getQuarter as getQuarterJalali,
  getISOWeeksInYear as getISOWeeksInYearJalali,
  getISOWeek as getISOWeekJalali,
  getISOWeekYear as getISOWeekYearJalali,
  setISOWeek as setISOWeekJalali,
  setISOWeekYear as setISOWeekYearJalali,
  getISODay as getISODayJalali,
  setISODay as setISODayJalali,
  isSameISOWeek as isSameISOWeekJalali,
  isSameISOWeekYear as isSameISOWeekYearJalali,
  isThisISOWeek as isThisISOWeekJalali,
  isLeapYear as isLeapYearJalali,
  getDaysInMonth as getDaysInMonthJalali,
  getDaysInYear as getDaysInYearJalali,
  getWeeksInMonth as getWeeksInMonthJalali,
} from 'date-fns-jalali';
