'use client';

import React from 'react';
import { 
  Palette, Lightbulb, Heart, Star, Camera, Video, Music, Mic,
  Book, Pen, Pencil, Brush, Scissors, Wand, Sparkles, Gift,
  Cake, Coffee, Pizza, ShoppingBag, CreditCard, DollarSign, TrendingUp,
  BarChart, PieChart, Activity, Target, Award, Trophy, Medal,
  Users, User, UserPlus, UserCheck, Smile, Laugh, Frown, Meh,
  MessageCircle, MessageSquare, Phone, Mail, Send, Share, Download,
  Upload, Link, ExternalLink, Copy, Edit, Trash, Save, Plus,
  Minus, X, Check, AlertCircle, Info, HelpCircle, Shield, Lock,
  Unlock, Eye, EyeOff, Settings, Cog, Wrench, Tool, Hammer,
  Home, Building, MapPin, Globe, Compass, Navigation, Flag, Map,
  Calendar, Clock, Timer, Stopwatch, Sun, Moon, Cloud, CloudRain,
  Zap, Flame, Snowflake, Wind, Droplet, Thermometer, Umbrella,
  Car, Truck, Bike, Plane, Train, Ship, Rocket, Bus,
  Gamepad, Dice, Puzzle, Chess, Cards, Dice1, Dice2, Dice3,
  Dice4, Dice5, Dice6, Play, Pause, Stop, SkipBack, SkipForward,
  Volume2, VolumeX, Headphones, Radio, Tv, Monitor, Laptop, Smartphone,
  Tablet, Watch, Mouse, Keyboard, Printer, Scanner, HardDrive, Database,
  Server, Wifi, Bluetooth, Battery, Plug, Power, Cpu, MemoryStick,
  Folder, File, FileText, FileImage, FileVideo, FileAudio, Archive,
  Package, Box, Layers, Grid, List, Layout, Sidebar, Menu,
  MoreHorizontal, MoreVertical, Ellipsis, ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Move, RotateCw, RotateCcw, RefreshCw,
  RefreshCcw, Repeat, Shuffle, Maximize, Minimize, Maximize2, Minimize2, Expand,
  Compress, ZoomIn, ZoomOut, Search, Filter, SortAsc, SortDesc, ArrowUpDown,
  ArrowUpAZ, ArrowDownAZ, ArrowUp01, ArrowDown01, Hash, Asterisk, Percent, Equal,
  NotEqual, LessThan, GreaterThan, PlusCircle, MinusCircle, XCircle, CheckCircle,
  AlertTriangle, AlertOctagon, QuestionMarkCircle,
  Ban, XOctagon, ShieldCheck, ShieldAlert, ShieldX, Key, Fingerprint, Glasses,
  Sunrise, Sunset, CloudSnow, CloudLightning, CloudDrizzle, CloudHail, CloudFog,
  Tornado, Hurricane, ThermometerSun, ThermometerSnow, Droplets, UmbrellaOff, Rainbow,
  Bolt, StarOff, HeartOff, ThumbsUp, ThumbsDown, Angry, Sad, Wink, Tongue, Kiss
} from 'lucide-react';

import { cn } from '@/lib/utils';

interface DynamicLucideIconProps {
  iconName?: string;
  className?: string;
  fallbackIcon?: React.ComponentType<{ className?: string }>;
  size?: number;
}

// Create a mapping of icon names to components
const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  'Palette': Palette,
  'Lightbulb': Lightbulb,
  'Heart': Heart,
  'Star': Star,
  'Camera': Camera,
  'Video': Video,
  'Music': Music,
  'Mic': Mic,
  'Book': Book,
  'Pen': Pen,
  'Pencil': Pencil,
  'Brush': Brush,
  'Scissors': Scissors,
  'Wand': Wand,
  'Sparkles': Sparkles,
  'Gift': Gift,
  'Cake': Cake,
  'Coffee': Coffee,
  'Pizza': Pizza,
  'ShoppingBag': ShoppingBag,
  'CreditCard': CreditCard,
  'DollarSign': DollarSign,
  'TrendingUp': TrendingUp,
  'BarChart': BarChart,
  'PieChart': PieChart,
  'Activity': Activity,
  'Target': Target,
  'Award': Award,
  'Trophy': Trophy,
  'Medal': Medal,
  'Users': Users,
  'User': User,
  'UserPlus': UserPlus,
  'UserCheck': UserCheck,
  'Smile': Smile,
  'Laugh': Laugh,
  'Frown': Frown,
  'Meh': Meh,
  'MessageCircle': MessageCircle,
  'MessageSquare': MessageSquare,
  'Phone': Phone,
  'Mail': Mail,
  'Send': Send,
  'Share': Share,
  'Download': Download,
  'Upload': Upload,
  'Link': Link,
  'ExternalLink': ExternalLink,
  'Copy': Copy,
  'Edit': Edit,
  'Trash': Trash,
  'Save': Save,
  'Plus': Plus,
  'Minus': Minus,
  'X': X,
  'Check': Check,
  'AlertCircle': AlertCircle,
  'Info': Info,
  'HelpCircle': HelpCircle,
  'Shield': Shield,
  'Lock': Lock,
  'Unlock': Unlock,
  'Eye': Eye,
  'EyeOff': EyeOff,
  'Settings': Settings,
  'Cog': Cog,
  'Wrench': Wrench,
  'Tool': Tool,
  'Hammer': Hammer,
  'Home': Home,
  'Building': Building,
  'MapPin': MapPin,
  'Globe': Globe,
  'Compass': Compass,
  'Navigation': Navigation,
  'Flag': Flag,
  'Map': Map,
  'Calendar': Calendar,
  'Clock': Clock,
  'Timer': Timer,
  'Stopwatch': Stopwatch,
  'Sun': Sun,
  'Moon': Moon,
  'Cloud': Cloud,
  'CloudRain': CloudRain,
  'Zap': Zap,
  'Flame': Flame,
  'Snowflake': Snowflake,
  'Wind': Wind,
  'Droplet': Droplet,
  'Thermometer': Thermometer,
  'Umbrella': Umbrella,
  'Car': Car,
  'Truck': Truck,
  'Bike': Bike,
  'Plane': Plane,
  'Train': Train,
  'Ship': Ship,
  'Rocket': Rocket,
  'Bus': Bus,
  'Gamepad': Gamepad,
  'Dice': Dice,
  'Puzzle': Puzzle,
  'Chess': Chess,
  'Cards': Cards,
  'Dice1': Dice1,
  'Dice2': Dice2,
  'Dice3': Dice3,
  'Dice4': Dice4,
  'Dice5': Dice5,
  'Dice6': Dice6,
  'Play': Play,
  'Pause': Pause,
  'Stop': Stop,
  'SkipBack': SkipBack,
  'SkipForward': SkipForward,
  'Volume2': Volume2,
  'VolumeX': VolumeX,
  'Headphones': Headphones,
  'Radio': Radio,
  'Tv': Tv,
  'Monitor': Monitor,
  'Laptop': Laptop,
  'Smartphone': Smartphone,
  'Tablet': Tablet,
  'Watch': Watch,
  'Mouse': Mouse,
  'Keyboard': Keyboard,
  'Printer': Printer,
  'Scanner': Scanner,
  'HardDrive': HardDrive,
  'Database': Database,
  'Server': Server,
  'Wifi': Wifi,
  'Bluetooth': Bluetooth,
  'Battery': Battery,
  'Plug': Plug,
  'Power': Power,
  'Cpu': Cpu,
  'MemoryStick': MemoryStick,
  'Folder': Folder,
  'File': File,
  'FileText': FileText,
  'FileImage': FileImage,
  'FileVideo': FileVideo,
  'FileAudio': FileAudio,
  'Archive': Archive,
  'Package': Package,
  'Box': Box,
  'Layers': Layers,
  'Grid': Grid,
  'List': List,
  'Layout': Layout,
  'Sidebar': Sidebar,
  'Menu': Menu,
  'MoreHorizontal': MoreHorizontal,
  'MoreVertical': MoreVertical,
  'Ellipsis': Ellipsis,
  'ChevronUp': ChevronUp,
  'ChevronDown': ChevronDown,
  'ChevronLeft': ChevronLeft,
  'ChevronRight': ChevronRight,
  'ArrowUp': ArrowUp,
  'ArrowDown': ArrowDown,
  'ArrowLeft': ArrowLeft,
  'ArrowRight': ArrowRight,
  'Move': Move,
  'RotateCw': RotateCw,
  'RotateCcw': RotateCcw,
  'RefreshCw': RefreshCw,
  'RefreshCcw': RefreshCcw,
  'Repeat': Repeat,
  'Shuffle': Shuffle,
  'Maximize': Maximize,
  'Minimize': Minimize,
  'Maximize2': Maximize2,
  'Minimize2': Minimize2,
  'Expand': Expand,
  'Compress': Compress,
  'ZoomIn': ZoomIn,
  'ZoomOut': ZoomOut,
  'Search': Search,
  'Filter': Filter,
  'SortAsc': SortAsc,
  'SortDesc': SortDesc,
  'ArrowUpDown': ArrowUpDown,
  'ArrowUpAZ': ArrowUpAZ,
  'ArrowDownAZ': ArrowDownAZ,
  'ArrowUp01': ArrowUp01,
  'ArrowDown01': ArrowDown01,
  'Hash': Hash,
  'Asterisk': Asterisk,
  'Percent': Percent,
  'Equal': Equal,
  'NotEqual': NotEqual,
  'LessThan': LessThan,
  'GreaterThan': GreaterThan,
  'PlusCircle': PlusCircle,
  'MinusCircle': MinusCircle,
  'XCircle': XCircle,
  'CheckCircle': CheckCircle,
  'AlertTriangle': AlertTriangle,
  'AlertOctagon': AlertOctagon,
  'QuestionMarkCircle': QuestionMarkCircle,
  'Ban': Ban,
  'XOctagon': XOctagon,
  'ShieldCheck': ShieldCheck,
  'ShieldAlert': ShieldAlert,
  'ShieldX': ShieldX,
  'Key': Key,
  'Fingerprint': Fingerprint,
  'Glasses': Glasses,
  'Sunrise': Sunrise,
  'Sunset': Sunset,
  'CloudSnow': CloudSnow,
  'CloudLightning': CloudLightning,
  'CloudDrizzle': CloudDrizzle,
  'CloudHail': CloudHail,
  'CloudFog': CloudFog,
  'Tornado': Tornado,
  'Hurricane': Hurricane,
  'ThermometerSun': ThermometerSun,
  'ThermometerSnow': ThermometerSnow,
  'Droplets': Droplets,
  'UmbrellaOff': UmbrellaOff,
  'Rainbow': Rainbow,
  'Bolt': Bolt,
  'StarOff': StarOff,
  'HeartOff': HeartOff,
  'ThumbsUp': ThumbsUp,
  'ThumbsDown': ThumbsDown,
  'Angry': Angry,
  'Sad': Sad,
  'Wink': Wink,
  'Tongue': Tongue,
  'Kiss': Kiss
};

export function DynamicLucideIcon({
  iconName,
  className,
  fallbackIcon: FallbackIcon,
  size = 16,
}: DynamicLucideIconProps) {
  if (!iconName) {
    return FallbackIcon ? (
      <FallbackIcon className={className} />
    ) : (
      <HelpCircle className={cn('text-gray-400', className)} />
    );
  }

  const IconComponent = iconMap[iconName];

  if (!IconComponent) {
    console.warn(`Icon "${iconName}" not found in iconMap`);
    return FallbackIcon ? (
      <FallbackIcon className={className} />
    ) : (
      <HelpCircle className={cn('text-gray-400', className)} />
    );
  }

  return <IconComponent className={className} />;
}
